repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=crlf]
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        require_serial: true
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        require_serial: true
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        require_serial: true
        types: [python]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        require_serial: true
        types: [python]
