repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        require_serial: true
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        require_serial: true
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        require_serial: true
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        require_serial: true
        types: [python]
      - id: pydocstyle
        name: pydocstyle
        entry: poetry run pydocstyle
        language: system
        require_serial: true
        types: [python]
