version: "3.8"
services:
  # IDE in browser
  ide:
    build:
      context: .
      target: ide
    env_file:
      - .env
    image: project_ide
    container_name: project_ide
    ports:
      - 8123:8123
    volumes:
      - .:/home/root/app/.
      - pre-commit:/root/.cache/pre-commit
      - poetry-cache:/root/.cache/pypoetry
      - ssh-cache:/root/.ssh/
      - $SSH_AUTH_SOCK:/tmp/authsock
      - $HOME/.gitconfig:/root/.gitconfig
    environment:
      SSH_AUTH_SOCK: /tmp/authsock
    command: bash -c "poetry run pre-commit install && code-server --auth none --bind-addr 0.0.0.0:8123 /home/root/app"

volumes:
  pre-commit:
  poetry-cache:
  ssh-cache:
